In [1]:
import matplotlib.image as mpimg
import numpy as np
import matplotlib.pyplot as plt
import os,sys
from scipy import ndimage, misc
from helpers import *
import skimage.transform as st
import cv2 as cv
import imageio
from PIL import Image

In [2]:
from helpers import *
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
def patch_to_label(patch):
    """Maps a BW white patch image to a label using thresholding """
    df = np.mean(patch)
    if df > 0.25:
        return 1
    else:
        return 0

In [4]:
# Loaded a set of images
root_dir = "training/"
image_dir = root_dir + "images/"
files = os.listdir(image_dir)
n = 100 # 100 images

print("Loading " + str(n) + " images")
imgs = [load_image(image_dir + files[i]) for i in range(n)]
print(files[0])

gt_dir = root_dir + "groundtruth/"
print("Loading " + str(n) + " images")
gt_imgs = [load_image(gt_dir + files[i]) for i in range(n)]

Loading 100 images
satImage_666.png
Loading 100 images


In [11]:
flat=np.ndarray.flatten(gt_imgs[3])
print(flat.shape)

(160000,)


In [22]:
for n in range(100):
    y= patch_to_label(gt_imgs[n])
    if y == 1:
        print(y)
        y=keras.utils.to_categorical(patch_to_label(gt_imgs[n]), num_classes = 2)

        print("to cat",y)

1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]
1
to cat [0. 1.]


In [102]:
## DATA AUGMENTATION, rotate every image by a certain angle.

#width, height for image crop
w,h = 400,400 

#iterator for correct names for the images
j=0

for i in range(100):
    #for angle in (15,30):
    for angle in (15,30,45,60,90,100,180,270): 
        img = imgs[i]
        img_gt = gt_imgs[i]

        ## IMAGE
        img_changed = ndimage.rotate(img, angle, reshape=True,mode='mirror') #rotate image
        img_final = img_crop(img_changed,w,h)
        img_final=img_float_to_uint8(img_final[0])

        ## GROUNDTRUTH
        gt_img_changed = ndimage.rotate(img_gt, angle, reshape=True,mode='mirror') #rotate groundtruth
        gt_img_final = img_crop(gt_img_changed,w,h)
        gt_img_final=img_float_to_uint8(gt_img_final[0])
        ret,gt_img_final = cv.threshold(gt_img_final,127,255,cv.THRESH_BINARY)

        ## SAVE IMAGES
        imageio.imwrite('training/images/satImage_{}.png'.format(j+101),img_final)        
        imageio.imwrite('training/groundtruth/satImage_{}.png'.format(j+101),gt_img_final)        

        j += 1

In [3]:
# Loaded a set of images
root_dir = "training/"
image_dir = root_dir + "images/"
files = os.listdir(image_dir)
n = 900 # 100 images

print("Loading " + str(n) + " images")
imgs = [load_image(image_dir + files[i]) for i in range(n)]
print(files[0])

gt_dir = root_dir + "groundtruth/"
print("Loading " + str(n) + " images")
gt_imgs = [load_image(gt_dir + files[i]) for i in range(n)]


Loading 900 images
satImage_666.png
Loading 900 images


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
